spring: 
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-aos:5432/aos_db}
    username: ${SPRING_DATASOURCE_USERNAME:aos_pg}
    password: ${SPRING_DATASOURCE_PASSWORD:Maryame1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: ALWAYS
      platform: POSTGRESQL
  mail: 
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}
    protocol: smtp
    properties: 
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
    sender: melkhalfi@insea.ac.ma
application:
  security:
    jwt:
      secret-key: 0Xft560/AaGtvlV7KqGlKPj8pBRubzWYxzGpvgg0LyRZdAi3WksRrhCq5myck+hJ
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: ALWAYS

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tryItOutEnabled: true


app:
  upload:
    allowed-extensions: pdf,jpg,jpeg,png,doc,docx