spring :
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
springdoc:
  default-produces-media-typa : application/json


server:
  port: 8089
  servlet:
    context-path: /AOS_MICEPP
    