services:
  postgres:
    container_name: postgres-aos
    image: postgres:15
    environment:
      POSTGRES_USER: aos_pg
      POSTGRES_PASSWORD: Maryame1234
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: aos_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - aos_network
    restart: unless-stopped

  mail-dev:
    container_name: maildev-aos
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - aos_network
    restart: unless-stopped

  backend:
    container_name: aos-backend
    build:
      context: ./aos_backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aos_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: aos_pg
      SPRING_DATASOURCE_PASSWORD: Maryame1234
      SPRING_MAIL_HOST: mail-dev
      SPRING_MAIL_PORT: 1025
      APPLICATION_MAILING_FRONTEND_ACTIVATION_URL: http://localhost:4200/activate-account
    ports:
      - "8089:8089"
    depends_on:
      - postgres
      - mail-dev
    networks:
      - aos_network
 
   

  frontend:
    container_name: aos-frontend
    build:
      context: ./aos_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - aos_network


networks:
  aos_network:
    driver: bridge

volumes:
  postgres:
    driver: local